version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: surprise-moments-db
    environment:
      POSTGRES_DB: surprise_moments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - surprise-network
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: surprise-moments-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - surprise-network
    restart: unless-stopped

  # Backend API Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: surprise-moments-server
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: surprise_moments
      DB_USER: postgres
      DB_PASSWORD: postgres_password
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      ENCRYPTION_KEY: your-32-character-encryption-key-here
      CLIENT_URL: http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ./server/uploads:/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - surprise-network
    restart: unless-stopped

  # Frontend React App
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: surprise-moments-client
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_ENVIRONMENT: production
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - surprise-network
    restart: unless-stopped

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: surprise-moments-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - client
      - server
    networks:
      - surprise-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  surprise-network:
    driver: bridge
