name: Build and deploy Node.js app to Azure Web App - surprise-gifting-student-api
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test (server)
        working-directory: server
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload server artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-app
          path: server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download server artifact
        uses: actions/download-artifact@v4
        with:
          name: server-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_799B7B0A95AF4B6486F3067D2EAA58AC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6C205D26B4B842E58CC276B4C015513D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7861EA0736944AFF92C4FE17C7A9BA80 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: surprise-gifting-student-api
          slot-name: Production
          package: server
